version: "3"

networks:
    app-net:

services:
    app:
        image: sandrofts/laravel
        container_name: app        
        networks:
            - app-net
        depends_on:
            - db
            - redis

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        networks:
            - app-net
        restart: always
        tty: true
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        volumes:
            - ./.docker/dbdata:/var/lib/mysql

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - app-net
        depends_on:
            - app

    redis:
        image: redis:alpine
        expose:
            - 6379
        networks:
            - app-net
